# Preparation part: run all of them

In [83]:
import pandas as pd
import logging
import numpy as np
import sys
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
import random
import math
import time
import numpy
from scipy.optimize import minimize
import math
import scipy
import sklearn

In [2]:
def compute_square_loss(X, y, theta):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)
    
    Returns:
        loss - the square loss, scalar
    """
    loss = 0 #initialize the square_loss
    #TODO
    
    part = np.dot(X,theta)-y
    loss = loss + np.dot(np.transpose(part),part)
    loss = loss/(2*int(y.shape[0]))
    
    return loss

In [3]:
def compute_square_loss(X, y, theta):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)
    
    Returns:
        loss - the square loss, scalar
    """
    loss = 0 #initialize the square_loss
    #TODO
    
    part = np.dot(X,theta)-y
    loss = loss + np.dot(np.transpose(part),part)
    loss = loss/(2*int(y.shape[0]))
    
    return loss

In [4]:
def compute_square_loss_gradient(X, y, theta):
    """
    Compute gradient of the square loss (as defined in compute_square_loss), at the point theta.
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D numpy array of size (num_features)
    
    Returns:
        grad - gradient vector, 1D numpy array of size (num_features)
    """
    #TODO
    grad = np.dot(np.transpose(theta),np.transpose(X))
    grad = np.dot(grad,X)
    grad = grad - np.dot(np.transpose(y),X)
    grad = grad/(int(y.shape[0]))
    
    return grad    

In [5]:
def batch_grad_descent(X, y, theta, alpha=0.1, num_iter=1000, check_gradient=False):
    """
    In this question you will implement batch gradient descent to
    minimize the square loss objective
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        alpha - step size in gradient descent
        num_iter - number of iterations to run 
        check_gradient - a boolean value indicating whether checking the gradient when updating
        
    Returns:
        theta_hist - store the the history of parameter vector in iteration, 2D numpy array of size (num_iter+1, num_features) 
                    for instance, theta in iteration 0 should be theta_hist[0], theta in ieration (num_iter) is theta_hist[-1]
        loss_hist - the history of objective function vector, 1D numpy array of size (num_iter+1) 
    """
    num_instances, num_features = int(X.shape[0]), int(X.shape[1])
    theta_hist = np.zeros((num_iter+1, num_features))  #Initialize theta_hist
    loss_hist = np.zeros(num_iter+1) #initialize loss_hist
    theta = np.expand_dims(np.ones(num_features), axis=1) #initialize theta
    #TODO
    
    if check_gradient==True:
        c = generic_gradient_checker(X, y, theta, compute_square_loss, compute_square_loss_gradient, epsilon=0.01, tolerance=1e-4)
        if c == True:
            for i in range(0,num_iter+1):    
                loss_hist[i] =  loss_hist[i]+compute_square_loss(X, y, theta)[0]
                theta_hist[i] = theta_hist[i]+np.transpose(theta)[0]
                g = compute_square_loss_gradient(X, y, theta) 
                if i >3 :
                    if sum(abs(theta_hist[i]-theta_hist[i-2]))/num_features<1e-3:
                        print ("iteration: %s times" % (i))
                        return (theta_hist,loss_hist)               
                
                g[0]= g[0]/math.sqrt(sum(np.multiply(g[0],g[0])))
                theta = theta-np.transpose(g)*alpha

            return (theta_hist,loss_hist)
        else:
            return (None,None)
    else:
        for i in range(0,num_iter+1):    
            loss_hist[i] =  loss_hist[i]+compute_square_loss(X, y, theta)[0]
            theta_hist[i] = theta_hist[i]+np.transpose(theta)[0]
            g = compute_square_loss_gradient(X, y, theta)
            if i >3 :
                if sum(abs(theta_hist[i]-theta_hist[i-2]))/num_features<1e-3:
                    print ("iteration: %s times" % (i))
                    return (theta_hist,loss_hist)  
            g[0]= g[0]/math.sqrt(sum(np.multiply(g[0],g[0])))
            theta = theta-np.transpose(g)*alpha

        return (theta_hist,loss_hist)

In [6]:
def compute_regularized_square_loss_gradient(X, y, theta, lambda_reg):
    """
    Compute the gradient of L2-regularized square loss function given X, y and theta
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D numpy array of size (num_features)
        lambda_reg - the regularization coefficient
    
    Returns:
        grad - gradient vector, 1D numpy array of size (num_features)
    """
    #TODO
    grad = np.dot(np.transpose(theta),np.transpose(X))
    grad = np.dot(grad,X)
    grad = grad - np.dot(np.transpose(y),X)
    grad = grad/(int(y.shape[0]))
    grad = grad + 2 * lambda_reg * np.transpose(theta)
    
    return grad    

In [7]:
def compute_regularized_square_loss(X, y, theta, lambda_reg):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)
    
    Returns:
        loss - the square loss, scalar
    """
    loss = 0 #initialize the square_loss
    #TODO
    
    part = np.dot(X,theta)-y
    loss = loss + np.dot(np.transpose(part),part)
    loss = loss/(2*int(y.shape[0]))
    loss = loss + lambda_reg *  np.dot(np.transpose(theta),theta)[0]
    
    return loss

In [8]:
def regularized_grad_descent(X, y,theta,  alpha=0.1, lambda_reg=1, num_iter=1000):
    """
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        alpha - step size in gradient descent
        lambda_reg - the regularization coefficient
        numIter - number of iterations to run 
        
    Returns:
        theta_hist - the history of parameter vector, 2D numpy array of size (num_iter+1, num_features) 
        loss_hist - the history of regularized loss value, 1D numpy array
    """
    num_instances, num_features = int(X.shape[0]), int(X.shape[1])
    theta_hist = np.zeros((num_iter+1, num_features))  #Initialize theta_hist
    loss_hist = np.zeros(num_iter+1) #initialize loss_hist
    theta = np.expand_dims(np.ones(num_features), axis=1) #initialize theta
    #TODO
    for i in range(0,num_iter+1):    
        loss_hist[i] =  loss_hist[i]+compute_regularized_square_loss(X, y, theta, lambda_reg)[0]
        theta_hist[i] = theta_hist[i]+np.transpose(theta)[0]
        g = compute_regularized_square_loss_gradient(X, y, theta, lambda_reg)
        g[0]= g[0]/math.sqrt(sum(np.multiply(g[0],g[0])))
        theta = theta-np.transpose(g)*alpha

    return (theta_hist,loss_hist)

In [58]:
def find_l2_minimizer_lambda(X,y,Xt,yt,theta, lambda_start_log = -7.0,lambda_end_log = 3.0,num_iter=10):
    for i in range(0,10):
        loss={"train":[],"valid":[]}
        r = (lambda_end_log-lambda_start_log)/10
        lambda_range = []
        plots = []
        for i in range(0,num_iter):
            lambda_range.append(math.exp(math.log(10)*(lambda_start_log+r*i)))
        for i in lambda_range:
            a,b=regularized_grad_descent(X, y,theta,  alpha=0.1, lambda_reg=i, num_iter=1000)
            loss["train"].append(compute_regularized_square_loss(X, y, np.transpose(a[-2:-1]),i)[0])
            loss["valid"].append(compute_square_loss(Xt, yt, np.transpose(a[-2:-1]))[0])

        minl = loss["valid"].index(min(loss["valid"]))

        if minl == 0:
            lambda_end_log = lambda_start_log+r
        elif minl == len(lambda_range)-1:
            lambda_start_log = lambda_end_log-r
        else:
            if loss["valid"][minl-1]<loss["valid"][minl+1]:
                lambda_start_log = lambda_start_log + (minl-1)*r
                lambda_end_log = lambda_start_log + r
            else:
                lambda_start_log = lambda_start_log + (minl)*r
                lambda_end_log = lambda_start_log + r

    return lambda_range[loss["valid"].index(min(loss["valid"]))]


In [64]:
def find_l1_minimizer_lambda(X,y,Xt,yt,theta, lambda_start_log = -7.0,lambda_end_log = 3.0,num_iter=10):
    for i in range(0,10):
        loss={"train":[],"valid":[]}
        r = (lambda_end_log-lambda_start_log)/10
        lambda_range = []
        plots = []
        for i in range(0,num_iter):
            lambda_range.append(math.exp(math.log(10)*(lambda_start_log+r*i)))
        for i in lambda_range:
            a,b=coordinate_descent_lasso_vec(X, y, lambda_reg=i, w= theta, num_iter=1000, tol=1e-3)
            loss["train"].append(compute_lasso_square_loss(X, y, a,i)[0])
            loss["valid"].append(compute_square_loss(Xt, yt, a)[0])

        minl = loss["valid"].index(min(loss["valid"]))

        if minl == 0:
            lambda_end_log = lambda_start_log+r
        elif minl == len(lambda_range)-1:
            lambda_start_log = lambda_end_log-r
        else:
            if loss["valid"][minl-1]<loss["valid"][minl+1]:
                lambda_start_log = lambda_start_log + (minl-1)*r
                lambda_end_log = lambda_start_log + r
            else:
                lambda_start_log = lambda_start_log + (minl)*r
                lambda_end_log = lambda_start_log + r

    return lambda_range[loss["valid"].index(min(loss["valid"]))]


In [10]:
def analyze_the_sparsity(V,tol=0.001):
    a = 0.0
    t = 0.0
    for e in V:
        t = t + 1
        if abs(e) < tol:
            a = a + 1
            print True
    print ("%s supports against %s elements in total, %s" % (a,t,a/t))

In [11]:
def compute_lasso_square_loss(X, y, theta, lambda_reg):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)
    
    Returns:
        loss - the square loss, scalar
    """
    loss = 0 #initialize the square_loss
    #TODO
    
    part = np.dot(X,theta)-y
    loss = loss + np.dot(np.transpose(part),part)
    loss = loss/(2*int(y.shape[0]))
    loss = loss + lambda_reg *  sum(abs(theta))
    
    return loss

In [12]:
def coordinate_descent_lasso(X,y,lambda_reg,w,num_iter=1000,tol=1e-3):
    # initialize w
    n,d = X.shape
    n = int(n);d = int(d)
    
    try:
        l = len(w)
    except TypeError:
        l = 0
    
    if l == 0:
        if w == 0:
            w = np.expand_dims(np.zeros(d),axis = 1)    
        else:
            w = np.dot(np.transpose(X),X)
            w = w + lambda_reg * numpy.identity(d)
            w = numpy.matrix(w).I
            w = np.dot(w,np.transpose(X))
            w = np.dot(w,y)

            w = np.expand_dims(w.A1,axis = 1)
        
    w_i = w + 0
    w_l = w + 0
    
    a = np.expand_dims(np.zeros(d), axis=1)
    for i in range(0,d):
        for j in range(0,n):
            a[i] = a[i] + 2*(X[j:(j+1),i:(i+1)] * X[j:(j+1),i:(i+1)])

    for ii in range(0,num_iter): 
        
        c = np.expand_dims(np.zeros(d), axis=1)
        for i in range(0,d):
            for j in range(0,n):

                c[i] = c[i] + 2*(X[j:(j+1),i:(i+1)] * (y[j] - np.dot(X[j:(j+1)],w) + w[i] * X[j:(j+1),i:(i+1)]))


            if (abs(c[i]/a[i]) - lambda_reg/a[i]) > 0:
                w[i] = np.sign(c[i]*a[i]) * (abs(c[i]/a[i]) - lambda_reg / a[i])

            else:
                w[i] = 0        

        if (sum(abs(w)) - sum(abs(w_l)))/d < tol:
            print ii
            return w,w_i

        # print c
        w_l = w + 0
        
    print "not converging until max iteration",ii+1

    return w,w_i

## 1 Preliminaries
1.1 Dataset construction

In [13]:
X = np.random.rand(150,75)

In [14]:
X

array([[ 0.3698622 ,  0.64839331,  0.76807463, ...,  0.73917348,
         0.11692581,  0.10532022],
       [ 0.35775099,  0.72842651,  0.97819585, ...,  0.84916247,
         0.20325601,  0.05613429],
       [ 0.56667802,  0.3916695 ,  0.40301643, ...,  0.43844608,
         0.07407487,  0.08077372],
       ..., 
       [ 0.62298625,  0.85273665,  0.17045826, ...,  0.74635817,
         0.44461074,  0.88778269],
       [ 0.39516059,  0.39495975,  0.45716019, ...,  0.3366181 ,
         0.76790098,  0.55159187],
       [ 0.7256994 ,  0.70301292,  0.46259039, ...,  0.9641697 ,
         0.97032482,  0.20669141]])

In [15]:
theta = np.expand_dims(np.zeros(int(X.shape[1])), axis=1)

In [16]:
for i in range(0,10) : 
    if i % 2 == 0: theta[i]=-10; 
    else: theta[i]=10

In [17]:
np.random.randn(75,1)/math.sqrt(10) # set the variance of dgp of standart norm to 0.1

array([[-0.19488139],
       [-0.21114157],
       [ 0.01662259],
       [-0.37462974],
       [ 0.31754295],
       [ 0.3548649 ],
       [ 0.04744648],
       [ 0.19077058],
       [-0.08587524],
       [-0.05740759],
       [ 0.72455398],
       [ 0.33511134],
       [-0.0013784 ],
       [-0.17348269],
       [ 0.5084437 ],
       [ 0.24693755],
       [-0.23296642],
       [ 0.26557806],
       [-0.24238535],
       [-0.23036126],
       [-0.16842511],
       [-0.4604045 ],
       [-0.06706664],
       [-0.22949561],
       [-0.17365589],
       [ 0.2657224 ],
       [ 0.53485444],
       [ 0.5736443 ],
       [ 0.2388065 ],
       [-0.5508706 ],
       [-0.59182746],
       [-0.43519256],
       [-0.29945879],
       [ 0.04885954],
       [ 0.06084195],
       [ 0.24273091],
       [-0.04897566],
       [-0.34364291],
       [ 0.05348729],
       [-0.32926216],
       [-0.2545068 ],
       [ 0.65062967],
       [-0.12737902],
       [-0.12753802],
       [-0.07947553],
       [-0

In [18]:
y= np.dot(X,theta) 

In [19]:
y = y + (np.random.randn(150,1)/math.sqrt(10))

In [20]:
y

array([[ 13.20810044],
       [  1.12585232],
       [ -8.19513537],
       [ -0.81901926],
       [  9.51206732],
       [  7.98758843],
       [ -6.84413292],
       [ -0.45691219],
       [ -3.55960407],
       [ 16.49845738],
       [ -2.986933  ],
       [ -1.02166327],
       [  9.69877222],
       [  4.65514469],
       [  0.79368895],
       [  5.01196189],
       [ 15.8432394 ],
       [ -1.38364884],
       [ -9.90872743],
       [ 14.35689321],
       [  2.87195466],
       [ 14.73718524],
       [  2.33012568],
       [ 11.55064922],
       [ 19.58704429],
       [  2.05453364],
       [ -6.38468587],
       [  4.79118093],
       [-21.39523211],
       [  1.10440007],
       [ -0.18252006],
       [ -8.85282116],
       [ -9.00212767],
       [ -3.68441537],
       [ 11.78770134],
       [  2.14123368],
       [  2.75847842],
       [  4.41945515],
       [  3.9456184 ],
       [  0.38183429],
       [ -9.89221499],
       [ -9.17410934],
       [  3.54179686],
       [  6

In [21]:
train_y = y[0:80]
vld_y = y[80:100]
test_y = y[100:150]
train_X = X[0:80]
vld_X = X[80:100]
test_X = X[100:150]

1.2 Experiments with Ridge Regression

In [22]:
theta_ini = np.expand_dims(np.ones(int(X.shape[1])), axis=1)

In [23]:
best_lambda = find_minimizer_lambda(train_X,train_y,vld_X,vld_y,theta_ini,lambda_start_log = -7.0,lambda_end_log = 3.0,num_iter=10)

In [24]:
best_lambda

1.6749657078371515e-07

In [146]:
start_time = time.time()
coef1 = regularized_grad_descent(train_X, train_y,theta_ini,  alpha=0.1, lambda_reg=best_lambda, num_iter=10000)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.653000116348 seconds ---


In [142]:
coef1[0][-1]

array([ -8.38753494e+00,   8.15590868e+00,  -8.17686538e+00,
         9.05637686e+00,  -1.04030832e+01,   7.46296821e+00,
        -1.06739897e+01,   8.76678924e+00,  -1.11077215e+01,
         9.61528510e+00,   8.72504318e-01,   4.56836829e-01,
         1.16098629e+00,   1.23731276e+00,   2.48691509e-01,
         1.30259655e+00,  -6.52481443e-01,  -2.33136987e-01,
         1.18979248e+00,  -1.12747874e+00,   4.70307793e-01,
        -1.00145381e+00,   1.08420134e-03,   4.09434792e-03,
         8.17129369e-01,   2.28373839e+00,   4.39716700e-01,
        -2.06347186e-01,   2.87227842e-01,  -9.99136236e-01,
        -1.71869808e+00,   4.28988262e-02,   8.73364734e-01,
         3.63919247e-01,  -1.30714258e+00,   1.03902023e-01,
        -3.34475789e-01,  -2.60158018e-01,   1.45030733e+00,
         2.82418553e-01,  -4.79689780e-02,   1.35114104e+00,
         5.64745235e-01,   6.60975862e-01,   1.80067029e-01,
         5.99514237e-01,   6.35384112e-01,   6.85818769e-01,
        -2.29584127e+00,

In [99]:
coefb = batch_grad_descent(train_X, train_y, theta_ini, alpha=0.1, num_iter=1000, check_gradient=False)

In [100]:
coefb[0][-1]

array([-6.70931288,  7.36406523, -6.89141708,  9.18381806, -8.28091154,
        5.81122649, -8.10270854,  5.63811386, -9.95551567,  6.25629457,
        0.73096707, -0.62755444,  1.00608417,  1.51760554,  0.2515953 ,
       -0.86532725, -0.82982022, -0.32418693,  3.10827232, -0.9819107 ,
        1.93175779, -0.64760849,  1.99727694, -1.13936216,  0.270002  ,
        0.86710222,  0.79002471, -0.77011099,  0.38067527, -1.88886218,
       -1.63554336,  0.55065784,  1.83911768,  1.61138311, -1.03200312,
        1.4700127 , -0.75707283,  0.12597957,  1.01489577, -0.86319856,
       -0.08304562,  0.54676865, -0.99429005,  2.72758883,  0.72766969,
        0.39819359,  0.49282983,  1.44970108, -1.69322594,  0.66364001,
        0.50981739, -0.47497805,  2.16325113, -2.62515533, -1.44844469,
       -0.7428398 ,  0.02028832, -2.29331361, -1.02813626, -0.28171115,
        0.42739345, -1.05113648,  0.65521883,  0.22934128, -2.60619894,
       -1.37399944,  1.11689229,  0.46363601, -1.92531676,  2.09

In [166]:
for i in coef1[0][-1][10:]:
     if abs(i) < 10e-2:
            print True

True
True
True
True
True
True


In [126]:
from sklearn.linear_model import Ridge

In [163]:
clf = Ridge(alpha=0.1, fit_intercept=False, normalize=False, copy_X=True, max_iter=10000, 
                           tol=0.001, solver='auto', random_state=None)

In [164]:
start_time = time.time()
clf.fit(train_X, train_y) 
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.00100016593933 seconds ---


In [165]:
clf.coef_[0]

array([ -7.78036087,   7.83126148,  -7.65493605,   9.03018743,
        -9.64010326,   6.90852825,  -9.81799675,   7.64403118,
       -10.65555142,   8.42000558,   0.80135402,   0.09072341,
         1.16574773,   1.24686111,   0.22985519,   0.63587797,
        -0.74221385,  -0.28221061,   1.85731528,  -1.07502068,
         1.04766901,  -0.88558411,   0.68054148,  -0.40885002,
         0.59998705,   1.82974375,   0.53791519,  -0.48043933,
         0.31658172,  -1.21789313,  -1.6639058 ,   0.26273569,
         1.22557968,   0.71535627,  -1.15971798,   0.59085136,
        -0.51298077,  -0.0817734 ,   1.3173481 ,  -0.03076678,
        -0.01124342,   1.00789705,  -0.02534725,   1.26479906,
         0.37975918,   0.54919602,   0.5120877 ,   0.98634309,
        -2.02997435,   1.00995031,   1.10579658,  -0.40843186,
         1.18956771,  -2.16517309,  -0.92742071,  -0.28318507,
         0.47013218,  -0.86623007,  -0.92587959,   0.08463336,
         0.07038442,  -1.10749901,   0.43189232,   0.52

In [140]:
for i in clf.coef_[0][10:]:
     if abs(i) < 10e-3:
            print True

## 2 Coordinate Descent for Lasso (a.k.a. The Shooting algorithm)
2.1 Experiments with the Shooting Algorithm

In [102]:
start_time = time.time()
wa,wi = coordinate_descent_lasso(train_X,train_y,lambda_reg=0.01,w=1,num_iter=1000,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))

27
--- 1.85700011253 seconds ---


In [43]:
analyze_the_sparsity(wa,tol=0.1)

True
True
True
True
4.0 supports against 75.0 elements in total, 0.0533333333333


In [25]:
def find_max_lambda_homotopy(X,y):
    l = abs(np.dot(np.transpose(X),y))
    l_m = l[0]
    for i in l:
        if i > l_m:
            l_m =i
    return 2 * l_m

In [26]:
def homotopy_method(X, y, lambda_reg, coh=10,tole=1e-10):
    l_m = find_max_lambda_homotopy(X,y)
    intr = math.log(l_m / lambda_reg) / coh
    for i in range(0,coh+1):
        m1 = math.exp(math.log(max_lambda)-intr*i)
        if i == 0:
            wa,wi = coordinate_descent_lasso(X,y,lambda_reg=m1,w=0,num_iter=1000,tol=1e-2)
        else:
            if i == coh :
                wa,wi = coordinate_descent_lasso(X,y,lambda_reg=m1,w=wa,num_iter=1000,tol=tole)   
            else:
                wa,wi = coordinate_descent_lasso(X,y,lambda_reg=m1,w=wa,num_iter=1000,tol=1e-2)
    return wa   

In [114]:
start_time = time.time()
wa = homotopy_method(train_X, train_y, lambda_reg=0.01, coh=10, tole = 1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
compute_square_loss(vld_X, vld_y, wa)

# this is slower but gives lower empirical risks however the total number of iterations is not that big compared to ordinary descent

0
8
5
5
4
2
0
0
0
0
56
--- 6.20399999619 seconds ---


array([[ 0.50783839]])

In [218]:
start_time = time.time()
wa,wi = coordinate_descent_lasso(train_X,train_y,lambda_reg=0.01,w=1,num_iter=1000,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
print compute_square_loss(vld_X, vld_y, wa)
print compute_lasso_square_loss(train_X, train_y, wa, lambda_reg=0.01)

8
--- 0.688999891281 seconds ---
[[ 0.47855106]]
[[ 1.16732485]]


In [219]:
start_time = time.time()
wa,wi = coordinate_descent_lasso(train_X,train_y,lambda_reg=0.01,w=0,num_iter=1000,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
print compute_square_loss(vld_X, vld_y, wa)
print compute_lasso_square_loss(train_X, train_y, wa, lambda_reg=0.01)

21
--- 1.5720000267 seconds ---
[[ 2.73703575]]
[[ 1.45436057]]


### “vectorization”

In [66]:
def coordinate_descent_lasso_vec(X,y,lambda_reg,w,num_iter=1000,tol=1e-3):
    # initialize w
    n,d = X.shape
    n = int(n);d = int(d)
    
    try:
        l = len(w)
    except TypeError:
        l = 0
    
    if l == 0:
        if w == 0:
            w = np.expand_dims(np.zeros(d),axis = 1)    
        else:
            w = np.dot(np.transpose(X),X)
            w = w + lambda_reg * numpy.identity(d)
            w = numpy.matrix(w).I
            w = np.dot(w,np.transpose(X))
            w = np.dot(w,y)

            w = np.expand_dims(w.A1,axis = 1)
        
    w_i = w + 0
    w_l = w + 0
    
    a = np.expand_dims(np.zeros(d), axis=1)
    XX = np.dot(np.transpose(X),X)
    
    for i in range(0,d):
        a[i] = 2* XX[i:(i+1),i:(i+1)]

    for ii in range(0,num_iter): 
        
        c = np.expand_dims(np.zeros(d), axis=1)
        for i in range(0,d):
            c[i] = 2*np.dot(np.transpose(X[:,i:(i+1)]) , (y - np.dot(X,w) + w[i] * X[:,i:(i+1)]))
            
            if (abs(c[i]/a[i]) - lambda_reg/a[i]) > 0:
                w[i] = np.sign(c[i]*a[i]) * (abs(c[i]/a[i]) - lambda_reg / a[i])

            else:
                w[i] = 0        

        if (sum(abs(w)) - sum(abs(w_l)))/d < tol:
            #print ii
            return w,w_i
        # print c
        w_l = w + 0
        
    print "not converging until max iteration",ii+1

    return w,w_i

In [38]:
start_time = time.time()
wa,wi = coordinate_descent_lasso_vec(train_X,train_y,lambda_reg=0.01,w=1,num_iter=1000,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
compute_square_loss(vld_X, vld_y, wa)
# vec form is much faster than loop form

20
--- 0.280999898911 seconds ---


array([[ 0.24052104]])

# 5 [Optional] Projected SGD via Variable Splitting

In [31]:
def projected_stochastic_gradient(X, y, theta_p, theta_m, lambda_reg):
    
    N,d = int(X.shape[0]),int(X.shape[1])
    
    E = np.dot(X,theta_m) + y
    grad_p = 2 * np.dot(np.transpose(theta_p),np.transpose(X))
    grad_p = np.dot(grad_p,X)
    grad_p = grad_p - 2 * np.dot(np.transpose(E),X)
    grad_p = grad_p/(int(y.shape[0]))
    grad_p = grad_p + lambda_reg 
    grad_p = np.transpose(grad_p)

    F = np.dot(X,theta_p) - y
    grad_m = 2 * np.dot(np.transpose(theta_m),np.transpose(X))
    grad_m = np.dot(grad_m,X)
    grad_m = grad_m - 2 * np.dot(np.transpose(F),X)
    grad_m = grad_m/(int(y.shape[0]))
    grad_m = grad_m + lambda_reg 
    grad_m = np.transpose(grad_m)
    
    grad_p= grad_p/math.sqrt(sum(np.multiply(grad_p,grad_p)))
    grad_m= grad_m/math.sqrt(sum(np.multiply(grad_m,grad_m)))
            
    return (grad_p,grad_m)

In [71]:
def projected_stochastic_gradient_descent(X, y, alpha=0.1, lambda_reg=0.1, num_iter=1000,alpha_sqrt=False,tol=1e-5):
    """
    In this question you will implement stochastic gradient descent with a regularization term
    
    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        alpha - string or float. step size in gradient descent
                NOTE: In SGD, it's not always a good idea to use a fixed step size. Usually it's set to 1/sqrt(t) or 1/t
                if alpha is a float, then the step size in every iteration is alpha.
                if alpha == "1/sqrt(t)", alpha = 1/sqrt(t)
                if alpha == "1/t", alpha = 1/t
        lambda_reg - the regularization coefficient
        num_iter - number of epochs (i.e number of times) to go through the whole training set
    
    Returns:
        theta_hist - the history of parameter vector, 3D numpy array of size (num_iter, num_instances, num_features) 
        loss hist - the history of regularized loss function vector, 2D numpy array of size(num_iter, num_instances)
    """
        
    N, d = int(X.shape[0]), int(X.shape[1])
    
    theta_p = np.expand_dims(np.ones(d), axis=1) #initialize theta
    theta_m = np.expand_dims(np.zeros(d), axis=1) #initialize theta
    
    g_p_lag = 0
    g_m_lag = 0
    
    theta_p_hist = np.zeros((num_iter, N, d))  #Initialize theta_hist
    theta_m_hist = np.zeros((num_iter, N, d))  #Initialize theta_hist
    loss_hist = np.zeros((num_iter, N)) #Initialize loss_hist
    g_p_hist = np.zeros((num_iter, N, d))
    
    alpha =  alpha / (1+ alpha *lambda_reg)
    
    for i in range(0,num_iter):
        
        if alpha_sqrt==False: alpha=1.0/(i+1)
        else: alpha=1.0/math.sqrt(i+1)
        
        for j in range(0,N):
            theta = theta_p - theta_m
            loss_hist[i][j] =  loss_hist[i][j]+ compute_lasso_square_loss(X[j:j+1], y[j:j+1], theta, lambda_reg)[0]
            theta_p_hist[i][j] = theta_p_hist[i][j]+ np.transpose(theta_p)[0]
            theta_m_hist[i][j] = theta_m_hist[i][j]+ np.transpose(theta_m)[0]
            g_p,g_m = projected_stochastic_gradient(X[j:j+1], y[j:j+1], theta_p, theta_m, lambda_reg)
            
            g_p_hist[i][j] = g_p_hist[i][j]+ np.transpose(g_p)[0]
            

            if j > 3:

                if sum(np.transpose(sum(abs(g_p+g_m+g_p_lag+g_m_lag)))*alpha)/(2*d) < tol:
                    
                    print ("iteration: %s times; now on %sth instance" % (i,j))
                    return (theta_p_hist,theta_m_hist,loss_hist)
                                                 
            theta_p = theta_p-g_p*alpha
            theta_m = theta_m-g_m*alpha
            
            for k in range(0,int(theta_p.shape[0])):
                if theta_p[k] < 0:
                    theta_p[k] = 0
                if theta_m[k] < 0:
                    theta_m[k] = 0
                    
            g_p_lag = g_p
            g_m_lag = g_m 
            

    return (theta_p_hist,theta_m_hist,loss_hist)
    #TODO

In [55]:
start_time = time.time()
a,b,c= projected_stochastic_gradient_descent(train_X, train_y, alpha=0.1, lambda_reg=0.01, num_iter=1000,alpha_sqrt=False,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
theta = a[-1][-2:-1]-b[-1][-2:-1]
theta = np.transpose(theta)
compute_square_loss(vld_X, vld_y, theta)


--- 39.6700000763 seconds ---


projected SGD is slower than shooting algorithm but gives better results under the same number of iterations

In [68]:
lambda_f1 = find_l1_minimizer_lambda(train_X,train_y,vld_X,vld_y, theta=1, lambda_start_log = -7.0,lambda_end_log = 3.0, num_iter=10)

In [73]:
start_time = time.time()
a,b,c= projected_stochastic_gradient_descent(train_X, train_y, alpha=0.1, lambda_reg=lambda_f1, num_iter=1000,alpha_sqrt=True,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
theta = a[-1][-2:-1]-b[-1][-2:-1]
theta = np.transpose(theta)
compute_square_loss(vld_X, vld_y, theta)

--- 39.1119999886 seconds ---


array([[ 0.14996966]])

### **` alpha_sqrt=True decreases alpha too fast that loss is not minimized, alpha_sqrt=False is better, but notice that fixed alpha also achieves a level as low as alpha_sqrt=True` **

In [70]:
start_time = time.time()
wa,wi = coordinate_descent_lasso_vec(train_X,train_y,lambda_reg=lambda_f1,w=1,num_iter=1000,tol=1e-10)
print("--- %s seconds ---" % (time.time() - start_time))
compute_square_loss(vld_X, vld_y, wa)
# vec form is much faster than loop form

--- 0.0469999313354 seconds ---


array([[ 0.24152318]])

In [75]:
analyze_the_sparsity(theta,tol=0.001)

True
True
2.0 supports against 75.0 elements in total, 0.0266666666667


In [76]:
analyze_the_sparsity(wa,tol=0.001)

0.0 supports against 75.0 elements in total, 0.0


In [77]:
analyze_the_sparsity(wa,tol=0.01)

True
1.0 supports against 75.0 elements in total, 0.0133333333333


In [78]:
analyze_the_sparsity(theta,tol=0.01)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
19.0 supports against 75.0 elements in total, 0.253333333333


### **` pSGD-produced sparcity is more preciser that coordinate` **